apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drive-data
  labels:
    app.kubernetes.io/name: drive
    app.kubernetes.io/instance: drive
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
