apiVersion: v1
kind: Service
metadata:
  name: social
  labels:
    app.kubernetes.io/name: social
    app.kubernetes.io/instance: social
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
  selector:
    app.kubernetes.io/name: social
    app.kubernetes.io/instance: social
